In [1]:
import pandas as pd

In [30]:
emotiv = pd.read_csv('datasets/HeadsetData2023-05-03_23-33-26_EPOCX_182325_2023.05.03T23.33.29.07.00.md.pm.bp.csv')
eye = pd.read_csv('datasets/EyeTracking2023-05-03_23-33-26.csv')

In [31]:
eye['Timestamp'] = (eye['Timestamp']/1000).astype(int)
emotiv['Timestamp'] = emotiv['Timestamp'].astype(int)

In [32]:
eye

      Timestamp           X           Y
0    1683182000  500.274372  499.901398
1    1683182000  503.078175  499.155832
2    1683182000  511.900882  497.546378
3    1683182001  529.960583  496.267070
4    1683182001  555.597081  496.214530
..          ...         ...         ...
534  1683182054  941.252831  464.718258
535  1683182054  895.084918  531.453396
536  1683182054  875.380661  568.613268
537  1683182054  827.581388  589.518115
538  1683182054  791.305442  625.781705

[539 rows x 3 columns]

In [33]:
emotiv

,Timestamp,MOT.CounterMems,MOT.InterpolatedMems,MOT.Q0,MOT.Q1,MOT.Q2,MOT.Q3,MOT.AccX,MOT.AccY,MOT.AccZ,...,POW.F8.Theta,POW.F8.Alpha,POW.F8.BetaL,POW.F8.BetaH,POW.F8.Gamma,POW.AF4.Theta,POW.AF4.Alpha,POW.AF4.BetaL,POW.AF4.BetaH,POW.AF4.Gamma
0,1683182009,28.0,0.0,0.474835,0.362183,-0.631042,0.495117,0.944451,-0.287633,-0.065926,...,1.944061,0.684509,0.569313,0.303171,0.307204,2.126520,0.684346,0.438793,0.231062,0.195456
1,1683182009,29.0,0.0,0.474852,0.362183,-0.630981,0.495178,0.944451,-0.287633,-0.065926,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1683182009,30.0,0.0,0.474992,0.361938,-0.630920,0.495300,0.940544,-0.268099,-0.052741,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1683182009,31.0,0.0,0.474980,0.362122,-0.630920,0.495178,0.947381,-0.282261,-0.059089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1683182009,0.0,0.0,0.474830,0.361938,-0.631042,0.495300,0.932243,-0.265657,-0.055671,...,1.974206,0.556068,0.458804,0.273979,0.301275,1.985103,0.598359,0.415264,0.201137,0.187395
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
641,1683182029,29.0,0.0,0.474429,0.364746,-0.630493,0.494324,0.946893,-0.276401,-0.058601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
642,1683182029,30.0,0.0,0.474574,0.364685,-0.630371,0.494385,0.946893,-0.276401,-0.058601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643,1683182029,31.0,0.0,0.474736,0.364685,-0.630249,0.494385,0.938591,-0.275913,-0.059089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644,1683182029,0.0,0.0,0.474736,0.364685,-0.630249,0.494385,0.942010,-0.279819,-0.054206,...,17.337271,2.166881,0.337335,0.452225,0.307839,3.633197,1.851165,0.387845,0.333859,0.214685
645,1683182029,1.0,0.0,0.474689,0.364807,-0.630310,0.494263,0.945428,-0.268587,-0.065926,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
merged = emotiv.merge(eye, on='Timestamp', how='left')

In [27]:
merged.to_csv('merged.csv', index='False')